name: Build C++ (Linux)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y \
          build-essential \
          libglfw3-dev \
          libgl1-mesa-dev \
          libxi-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev

      - name: Compilar projeto
        run: make -C Projeto
